### PR TITLE
Update ubi8 to use latest in Dockerfile

### PR DESCRIPTION
**Pull request by hsong-rh**

### CODE REVIEW

**Review by eclarizio — COMMENTED** [review]
What's the reasoning behind using `latest` instead of explicitly declaring the version of whatever the latest version is? My concern would be that if we aren't actively monitoring ubi updates and something breaks, this may be a difficult thing to remember to track down.

**Comment by mkanoor** [comment]
@eclarizio Quay is reporting vulnerabilities in the image we build. we are hoping using the latest ubi8 fixes the vulnerabilities that Quay is reporting.

**Comment by hsong-rh** [comment]
@eclarizio @mkanoor After changed to use latest ubi8, there are no vulnerabilities in quay images.

**Comment by eclarizio** [comment]
> @eclarizio @mkanoor After changed to use latest ubi8, there are no vulnerabilities in quay images.
> 
> https://quay.io/repository/cloudservices/catalog_inventory-api/manifest/sha256:946ee1bc0a41c0cf329ff47ccf352d547eeb9c243622dbdde0b8c5e01c6450a8?tab=vulnerabilities

I understand it fixes an issue right now, my question is more around why are we using `latest` instead of say, `8.2-344` or `8.3-1` or whatever the latest actual version number is? I personally don't really have a problem behind using `latest`, I was just making sure that we know if we use `latest`, we may be getting updates we don't know.

**Comment by hsong-rh** [comment]
@eclarizio The `latest` tag is changed to the exact version `8.3`

**Review by mkanoor — APPROVED** [review]

**Review by eclarizio — APPROVED** [review]

**Pull request merged**
